# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: &DEVELOPMENT
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: josh
  password:
  host: localhost
  port: 5432

test: &TEST
  <<: *DEVELOPMENT
  database: project_test

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: 
  password:
